//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Solution1.Module.BusinessObjects.Slowniki
{

    public partial class car_option_value : XPLiteObject
    {
        int fid_car_option_value;
        [Key]
        public int id_car_option_value
        {
            get { return fid_car_option_value; }
            set { SetPropertyValue<int>("id_car_option_value", ref fid_car_option_value, value); }
        }
        int fis_base;
        public int is_base
        {
            get { return fis_base; }
            set { SetPropertyValue<int>("is_base", ref fis_base, value); }
        }
        car_option fid_car_option;
        [Association(@"car_option_valueReferencescar_option")]
        public car_option id_car_option
        {
            get { return fid_car_option; }
            set { SetPropertyValue<car_option>("id_car_option", ref fid_car_option, value); }
        }
        car_equipment fid_car_equipment;
        [Association(@"car_option_valueReferencescar_equipment")]
        public car_equipment id_car_equipment
        {
            get { return fid_car_equipment; }
            set { SetPropertyValue<car_equipment>("id_car_equipment", ref fid_car_equipment, value); }
        }
        int fdate_create;
        [Browsable(false)]
        public int date_create
        {
            get { return fdate_create; }
            set { SetPropertyValue<int>("date_create", ref fdate_create, value); }
        }
        int fdate_update;
        [Browsable(false)]
        public int date_update
        {
            get { return fdate_update; }
            set { SetPropertyValue<int>("date_update", ref fdate_update, value); }
        }
        car_type fid_car_type;
        public car_type id_car_type
        {
            get { return fid_car_type; }
            set { SetPropertyValue<car_type>("id_car_type", ref fid_car_type, value); }
        }
    }

}
