//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Solution1.Module.BusinessObjects.Slowniki
{

    public partial class car_equipment : XPLiteObject
    {
        int fid_car_equipment;
        [Key(false)]
        public int id_car_equipment
        {
            get { return fid_car_equipment; }
            set { SetPropertyValue<int>("id_car_equipment", ref fid_car_equipment, value); }
        }
        string fname;
        [Size(255)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        int fdate_create;
        public int date_create
        {
            get { return fdate_create; }
            set { SetPropertyValue<int>("date_create", ref fdate_create, value); }
        }
        int fdate_update;
        public int date_update
        {
            get { return fdate_update; }
            set { SetPropertyValue<int>("date_update", ref fdate_update, value); }
        }
        car_trim fid_car_trim;
        [Association(@"car_equipmentReferencescar_trim")]
        public car_trim id_car_trim
        {
            get { return fid_car_trim; }
            set { SetPropertyValue<car_trim>("id_car_trim", ref fid_car_trim, value); }
        }
        car_type fid_car_type;
        [Association(@"car_equipmentReferencescar_type")]
        public car_type id_car_type
        {
            get { return fid_car_type; }
            set { SetPropertyValue<car_type>("id_car_type", ref fid_car_type, value); }
        }
        int fyear;
        public int year
        {
            get { return fyear; }
            set { SetPropertyValue<int>("year", ref fyear, value); }
        }
        [Association(@"car_option_valueReferencescar_equipment")]
        public XPCollection<car_option_value> car_option_values { get { return GetCollection<car_option_value>("car_option_values"); } }
    }

}
