//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using DevExpress.ExpressApp.DC;

namespace Solution1.Module.BusinessObjects.Slowniki
{

    public partial class car_model : XPLiteObject
    {
        int fid_car_model;
        [Key(false)]
        [Browsable(false)]
        public int id_car_model
        {
            get { return fid_car_model; }
            set { SetPropertyValue<int>("id_car_model", ref fid_car_model, value); }
        }
        car_make fid_car_make;
        [Association(@"car_modelReferencescar_make")]
        [XafDisplayName("Producent")]
        public car_make id_car_make
        {
            get { return fid_car_make; }
            set { SetPropertyValue<car_make>("id_car_make", ref fid_car_make, value); }
        }
        string fname;
        [Size(255)]
        [XafDisplayName("Model")]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        int fdate_create;
        [Browsable(false)]
        public int date_create
        {
            get { return fdate_create; }
            set { SetPropertyValue<int>("date_create", ref fdate_create, value); }
        }
        int fdate_update;
        [Browsable(false)]
        public int date_update
        {
            get { return fdate_update; }
            set { SetPropertyValue<int>("date_update", ref fdate_update, value); }
        }

        [XafDisplayName("Typ")]
        car_type fid_car_type;
        [Association(@"car_modelReferencescar_type")]
        public car_type id_car_type
        {
            get { return fid_car_type; }
            set { SetPropertyValue<car_type>("id_car_type", ref fid_car_type, value); }
        }

        bool archiwalny;
        [XafDisplayName("Archiwalny")]
        public bool Archiwalny
        {
            get
            {
                return archiwalny;
            }
            set
            {
                SetPropertyValue("Archiwalny", ref archiwalny, value);
            }
        }

        [XafDisplayName("Serie")]
        [Association(@"car_serieReferencescar_model"), DevExpress.Xpo.Aggregated]
        
        public XPCollection<car_serie> car_series { get { return GetCollection<car_serie>("car_series"); } }
        [XafDisplayName("Wersje")]
        [Association(@"car_trimReferencescar_model"), DevExpress.Xpo.Aggregated]
        public XPCollection<car_trim> car_trims { get { return GetCollection<car_trim>("car_trims"); } }
        [XafDisplayName("Generacje")]
        [Association(@"car_generationReferencescar_model"), DevExpress.Xpo.Aggregated]
        public XPCollection<car_generation> car_generations { get { return GetCollection<car_generation>("car_generations"); } }
    }

}
