//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Solution1.Module.BusinessObjects.Slowniki
{

    public partial class car_specification : XPLiteObject
    {
        int fid_car_specification;
        [Key(false)]
        public int id_car_specification
        {
            get { return fid_car_specification; }
            set { SetPropertyValue<int>("id_car_specification", ref fid_car_specification, value); }
        }
        string fname;
        [Size(255)]
        public string name
        {
            get { return fname; }
            set { SetPropertyValue<string>("name", ref fname, value); }
        }
        int fid_parent;
        public int id_parent
        {
            get { return fid_parent; }
            set { SetPropertyValue<int>("id_parent", ref fid_parent, value); }
        }
        int fdate_create;
        [Browsable(false)]
        public int date_create
        {
            get { return fdate_create; }
            set { SetPropertyValue<int>("date_create", ref fdate_create, value); }
        }
        int fdate_update;
        [Browsable(false)]
        public int date_update
        {
            get { return fdate_update; }
            set { SetPropertyValue<int>("date_update", ref fdate_update, value); }
        }
        car_type fid_car_type;
        [Association(@"car_specificationReferencescar_type")]
        public car_type id_car_type
        {
            get { return fid_car_type; }
            set { SetPropertyValue<car_type>("id_car_type", ref fid_car_type, value); }
        }
        [Association(@"car_specification_valueReferencescar_specification")]
        public XPCollection<car_specification_value> car_specification_values { get { return GetCollection<car_specification_value>("car_specification_values"); } }
    }

}
